// Data.js
export const productData = {
  id: "62f95e0e-a953-49a6-8544-04b88350b3d1",
  resultNumber: "1/2",
  title: {
    text: "Minimalist hair clip design held by hand in a bright indoor setting showcasing modern aesthetics",
    charCount: 90,
    wordCount: 15,
  },
  description: {
    text: "A person holds a sleek, modern black hair clip in a well-lit room, emphasizing its unique shape and stylish design. The background features neutral colors, enhancing the clip's elegance.",
    charCount: 166,
    wordCount: 29,
  },
  keywords: [
    { id: 1, text: "hair clip" },
    { id: 2, text: "black clip" },
    { id: 3, text: "modern design" },
    { id: 4, text: "stylish accessory" },
    { id: 5, text: "person holding" },
    { id: 6, text: "neutral background" },
    { id: 7, text: "elegance" },
    { id: 8, text: "unique shape" },
    { id: 9, text: "hair accessory" },
    { id: 10, text: "contemporary style" },
    { id: 11, text: "fashion accessory" },
    { id: 12, text: "chic look" },
    { id: 13, text: "salon" },
    { id: 14, text: "beauty" },
    { id: 15, text: "hair styling" },
    { id: 16, text: "everyday wear" },
    { id: 17, text: "personal style" },
    { id: 18, text: "light conditions" },
    { id: 19, text: "craftsmanship" },
    { id: 20, text: "texture" },
    { id: 21, text: "simplicity" },
    { id: 22, text: "versatility" },
    { id: 23, text: "minimalist design" },
    { id: 24, text: "quality materials" },
    { id: 25, text: "functional beauty" },
    { id: 26, text: "practical style" },
    { id: 27, text: "trend" },
    { id: 28, text: "pampering" },
    { id: 29, text: "grooming" },
    { id: 30, text: "aesthetics" },
    { id: 31, text: "modernism" },
    { id: 32, text: "subtle tones" },
    { id: 33, text: "casual elegance" },
  ],
  images: [
    {
      id: 1,
      src: "/resultpage/result1.jpeg",
      alt: "Vintage photographer with camera and flashlight",
      isMain: true,
      caption: "Vintage photographer holding camera with flashlight attachment",
    },
    {
      id: 2,
      src: "/resultpage/result2.jpeg",
      alt: "Unique brown infinity-shaped chair",
      isMain: false,
      caption: "Unique brown infinity-shaped chair designed for modern spaces",
    },
    {
      id: 3,
      src: "/resultpage/result3.jpeg",
      alt: "Minimalist hair clip design held by hand",
      isMain: false,
      caption:
        "Minimalist hair clip design held by hand in a bright indoor setting showcasing modern aesthetics",
    },
  ],
};
